version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    networks:
      - nginx_proxy
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: laravel-web
    restart: always
    ports:
      - "8081:80"    # Bu portu doğrudan kullanma, Proxy Manager yönetecek
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - nginx_proxy

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true

volumes:
  dbdata:
